# -*- coding: utf-8 -*-
"""Healthhcare2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wKQZ6w6ypoPu4NhcZSKyquL9rkeWs5VE
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("/content/healthcare_dataset.csv")

df.head()

df.columns

df.info()

df.isnull()

df['Medical_Code'].isnull().sum()

df['Medical_Code']=df['Medical_Code'].fillna('unknown')

df['Admission_Date']=pd.to_datetime(df['Admission_Date'])
df['Admission_Date']

df['Discharge_Date']=pd.to_datetime(df['Discharge_Date'], format='%d-%m-%Y')
df['Discharge_Date']

df['Admission_Type']=(
    df['Admission_Type']
    .str.strip()
    .str.lower()
    .str.title()
)
df['Admission_Type']

df['Billing_Amount'].describe()

import seaborn as sns

billing = df.groupby(['Medical_Condition', 'Gender'])['Billing_Amount'].sum().unstack()
billing

billing.plot(kind='bar',figsize=(10,6), stacked=True)

monthly_sub=df.groupby('Admission_Month').size()
monthly_sub

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,6))
sns.violinplot(data=df,
               x='Medical_Condition',
               y='Billing_Amount')

df['Admission_Month']=df['Admission_Date'].dt.month
df['Admission_Month']

monthly_sub = df['Admission_Month'].value_counts().sort_index()
monthly_sub.plot()