# -*- coding: utf-8 -*-
"""AAPL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eIayW2pImEqF_isF9FL_WvGzwoRAYUHX
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_excel("/content/AAPL.xlsx")

df.head()

df.info()

df.shape

df.dtypes

df.isnull()

df.duplicated()

print( df["Open"].mean())
print( df["Close"].mean())

df["Daily_return"] = ((df["Close"] - df["Open"]) / df["Open"]) * 100

df

price_cols = ['Open', 'High', 'Low', 'Close', 'Volume']

df[price_cols] = df[price_cols].apply(pd.to_numeric, errors='coerce')

df = df.dropna(subset=price_cols)
df = df.drop_duplicates()

df['Price_Delta'] = df['Close'] - df['Open']

df['Daily_Return'] = ((df['Close'] - df['Open']) / df['Open']) * 100

mean_volume = df['Volume'].mean()
std_volume = df['Volume'].std()

df['Volume_Anomaly'] = df['Volume'] > (mean_volume + 2 * std_volume)

anomalous_days = df[df['Volume_Anomaly']]

mean_return = df['Daily_Return'].mean()
variance_return = df['Daily_Return'].var()
std_return = df['Daily_Return'].std()

print("Mean Return:", mean_return)
print("Variance:", variance_return)
print("Standard Deviation:", std_return)