# -*- coding: utf-8 -*-
"""Student Performance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VRTRQoMA1KWyStCjOn1y7ATcT-0-nuMd
"""

from google.colab import files

uploaded = files.upload()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/StudentsPerformance.csv")

df.head()

df.tail()

df.isnull()

cat_cols = ['gender', 'race/ethnicity', 'parental level of education',
            'lunch', 'test preparation course']

for col in cat_cols:
    df[col] = df[col].str.strip()

for col in cat_cols:
    print(col, df[col].unique())

subjects = ['math score', 'reading score', 'writing score']

print(df[subjects].describe())

for col in subjects:
    print("\n", col)
    print("Mean:", df[col].mean())
    print("Median:", df[col].median())
    print("Standard Deviation:", df[col].std())
    print("Q1:", df[col].quantile(0.25))
    print("Q3:", df[col].quantile(0.75))

df['Total Marks'] = (
    df['math score'] +
    df['reading score'] +
    df['writing score']
)

df['Percentage'] = (df['Total Marks'] / 300) * 100

print(df[['Total Marks', 'Percentage']].head())

for col in subjects:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print("\nOutliers in", col)
    print(outliers[[col]])