# -*- coding: utf-8 -*-
"""AAPL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eIayW2pImEqF_isF9FL_WvGzwoRAYUHX
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_excel("/content/AAPL.xlsx")

df.head()

df.info()

df.shape

df.dtypes

df.isnull()

df.duplicated()

print( df["Open"].mean())
print( df["Close"].mean())

df["Daily_return"] = ((df["Close"] - df["Open"]) / df["Open"]) * 100

df

price_cols = ['Open', 'High', 'Low', 'Close', 'Volume']

df[price_cols] = df[price_cols].apply(pd.to_numeric, errors='coerce')

df = df.dropna(subset=price_cols)
df = df.drop_duplicates()

df['Price_Delta'] = df['Close'] - df['Open']

df['Daily_Return'] = ((df['Close'] - df['Open']) / df['Open']) * 100

mean_volume = df['Volume'].mean()
std_volume = df['Volume'].std()

df['Volume_Anomaly'] = df['Volume'] > (mean_volume + 2 * std_volume)

anomalous_days = df[df['Volume_Anomaly']]

mean_return = df['Daily_Return'].mean()
variance_return = df['Daily_Return'].var()
std_return = df['Daily_Return'].std()

print("Mean Return:", mean_return)
print("Variance:", variance_return)
print("Standard Deviation:", std_return)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 6))
plt.plot(df['Date'], df['Open'], label='Open')
plt.plot(df['Date'], df['High'], label='High')
plt.plot(df['Date'], df['Low'], label='Low')
plt.plot(df['Date'], df['Close'], label='Close')

plt.title('OHLC Prices Over Time')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(12, 5))
plt.plot(df['Date'], df['Volume'])

plt.title('Trading Volume Over Time')
plt.xlabel('Date')
plt.ylabel('Volume')
plt.xticks(rotation=45)
plt.show()

df['MA20'] = df['Close'].rolling(window=20).mean()
df['MA50'] = df['Close'].rolling(window=50).mean()

plt.figure(figsize=(12, 6))

plt.plot(df['Date'], df['Close'], label='Daily Close')
plt.plot(df['Date'], df['MA20'], label='20-Day MA')
plt.plot(df['Date'], df['MA50'], label='50-Day MA')

plt.title('Closing Price with Moving Averages')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10, 6))

sns.histplot(df['Daily_Return'], kde=True, bins=30)

plt.title('Distribution of Daily Returns')
plt.xlabel('Daily Return (%)')
plt.ylabel('Frequency')
plt.show()

mean_return = df['Daily_Return'].mean()
std_return = df['Daily_Return'].std()
max_return = df['Daily_Return'].max()
min_return = df['Daily_Return'].min()

print("Financial Summary")
print("-----------------")
print("Average Daily Return:", mean_return)
print("Standard Deviation:", std_return)
print("Maximum Daily Return:", max_return)
print("Minimum Daily Return:", min_return)