# -*- coding: utf-8 -*-
"""SP preprocessed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgHzJpkw4gvRMIF8Sg-ttS05skHmt-Tk
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/studentperformance_preprocessed.csv")

print(df.head())

print(df.columns)

grouped = df.groupby(
    ['parental level of education', 'lunch']
)[['math score', 'reading score', 'writing score']].mean()

print(grouped)

grouped.plot(
    kind='bar',
    figsize=(12, 6)
)

plt.title('Average Test Scores by Parental Education and Lunch Type')
plt.xlabel('Parental Education Level')
plt.ylabel('Average Score')
plt.xticks(rotation=45)
plt.legend(title='Subject')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 6))

sns.boxplot(
    x='test preparation course',
    y='math score',
    data=df
)

plt.title('Math Score Variation by Test Preparation')
plt.xlabel('Test Preparation Course')
plt.ylabel('Math Score')
plt.show()

plt.figure(figsize=(10, 6))

sns.boxplot(
    x='test preparation course',
    y='reading score',
    data=df
)

plt.title('Reading Score Variation by Test Preparation')
plt.xlabel('Test Preparation Course')
plt.ylabel('Reading Score')
plt.show()

plt.figure(figsize=(10, 6))

sns.boxplot(
    x='test preparation course',
    y='writing score',
    data=df
)

plt.title('Writing Score Variation by Test Preparation')
plt.xlabel('Test Preparation Course')
plt.ylabel('Writing Score')
plt.show()

plt.figure(figsize=(8, 6))

sns.scatterplot(
    x='math score',
    y='reading score',
    data=df
)

plt.title('Math Score vs Reading Score')
plt.xlabel('Math Score')
plt.ylabel('Reading Score')
plt.show()

plt.figure(figsize=(8, 6))

sns.scatterplot(
    x='math score',
    y='writing score',
    data=df
)

plt.title('Math Score vs Writing Score')
plt.xlabel('Math Score')
plt.ylabel('Writing Score')
plt.show()

plt.figure(figsize=(8, 6))

sns.scatterplot(
    x='reading score',
    y='writing score',
    data=df
)

plt.title('Reading Score vs Writing Score')
plt.xlabel('Reading Score')
plt.ylabel('Writing Score')
plt.show()

scores = df[
    ['math score', 'reading score', 'writing score']
]

correlation = scores.corr()

print(correlation)

plt.figure(figsize=(8, 6))

sns.heatmap(
    correlation,
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title('Correlation Heatmap of Student Scores')
plt.show()

df['average score'] = (
    df['math score'] +
    df['reading score'] +
    df['writing score']
) / 3

print(
    df.groupby('test preparation course')['average score'].mean()
)

print("Average scores by lunch type:")
print(
    df.groupby('lunch')[
        ['math score', 'reading score', 'writing score']
    ].mean()
)

print("\nAverage scores by parental education:")
print(
    df.groupby('parental level of education')[
        ['math score', 'reading score', 'writing score']
    ].mean()
)

print("\nAverage scores by test preparation:")
print(
    df.groupby('test preparation course')[
        ['math score', 'reading score', 'writing score']
    ].mean()
)

print("EDUCATIONAL EQUITY RECOMMENDATIONS")
print("----------------------------------")

print("1. Provide free test preparation programs to students.")
print("2. Give additional academic support to students from disadvantaged backgrounds.")
print("3. Provide learning resources and tutoring facilities.")
print("4. Monitor achievement gaps across different parental education levels.")
print("5. Provide additional support for students with lower scores.")
print("6. Encourage reading and writing programs because these scores show a strong relationship.")
print("7. Schools should regularly evaluate student performance data.")